# partial playbook just for this project to be able to compile documentation without pushing it to GitHub
# usage: antora generate antora-playbook.yml
site:
  title: SmallRye Reactive Messaging only documentation
  start_page: smallrye-reactive-messaging::index.adoc
content:
  sources:
    - url: ..
      start_path: doc
      branches: HEAD
ui:
  bundle:
    url: https://github.com/smallrye/smallrye-antora-ui/blob/master/build/ui-bundle.zip?raw=true
    snapshot: true
asciidoc:
  attributes:
    version: '1.1.0'
    weld-version: '3.1.3.Final'
    smallrye-streams-version: '1.0.10'
    smallrye-config-version: '1.6.2'
